# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Ashley Theiss"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Musings of a serial tech entrepreneur + full-stack web developer from Vancouver."

# Tagline near the site title
tagline: "Musings of a serial tech entrepreneur + full-stack web developer from Vancouver."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://ashleytheiss.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Projects
  url: /projects/
- text: Archives
  url: /tags/
# - text: Style Guide
#   url: /style-guide/
# ^^^ Follow this convention for additional static non-post pages. Create the corresponding .md file in the site root dir.

# The shortname for your Disqus site to enable comments.
disqus: ashleytheiss

# Author information - author info at the bottom of the post
author_name: "Ashley Theiss"
author_bio: "Ashley is a full-stack Lean tech entrepreneur, web developer, designer, photographer, DJ, and aspiring glider pilot, active the Vancouver tech community."
author_url:  "http://ashleytheiss.com"
author_location: "Vancouver, Canada"
author_image: /images/authorimage.png

# Sidebar Ad banner - turn this back on to use the sidebar ad banner!
# banner_url: "http://justgoodthemes.com"
# banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: "beforeyouknowit"
# facebook_username: "username"
# googleplus_username: "+username"
github_username: "beforeyouknowit"
# codepen_username: "username"
# dribbble_uername: "username"
medium_username: "@beforeyouknowit"
instagram_username: "beforeyouknowit"
# pinterest_username: "username"
linkedin_username: "ashleytheiss"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
